export const Events = {
  COMMENT_CREATED: 'COMMENT_CREATED',
  COMMENT_DELETED: 'COMMENT_DELETED',
  COMMENT_UPDATED: 'COMMENT_UPDATE',
  COMMENT_HIDDEN: 'COMMENT_HIDDEN',
  COMMENT_UNHIDDEN: 'COMMENT_UNHIDDEN',
  NOTIFICATION_CREATED: 'NOTIFICATION_CREATED',
};
