export const CREATE_COMMENT = 'CREATE_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const COMMENT_CREATED_NOTIFICATION = 'COMMENT_CREATED_NOTIFICATION';
